// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8MY4Jt5eiU3C7Dy23gOxVtM8i9bbJ--g',
    appId: '1:658506360235:web:cc54dbe5e1620ec92e5eee',
    messagingSenderId: '658506360235',
    projectId: 'v4c-app-72802',
    authDomain: 'v4c-app-72802.firebaseapp.com',
    storageBucket: 'v4c-app-72802.firebasestorage.app',
    measurementId: 'G-CK13CXW30P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjSMrdka93P2DVaTuoB1ahhK0zE9PU5xg',
    appId: '1:658506360235:android:7eed1fca13b375ee2e5eee',
    messagingSenderId: '658506360235',
    projectId: 'v4c-app-72802',
    storageBucket: 'v4c-app-72802.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVkNsZb-fFKx475Z6Z1XhzY-1ObjF2SL8',
    appId: '1:658506360235:ios:f40178db8181d3d02e5eee',
    messagingSenderId: '658506360235',
    projectId: 'v4c-app-72802',
    storageBucket: 'v4c-app-72802.firebasestorage.app',
    iosBundleId: 'com.example.v4cApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVkNsZb-fFKx475Z6Z1XhzY-1ObjF2SL8',
    appId: '1:658506360235:ios:f40178db8181d3d02e5eee',
    messagingSenderId: '658506360235',
    projectId: 'v4c-app-72802',
    storageBucket: 'v4c-app-72802.firebasestorage.app',
    iosBundleId: 'com.example.v4cApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8MY4Jt5eiU3C7Dy23gOxVtM8i9bbJ--g',
    appId: '1:658506360235:web:2594998a2794b91c2e5eee',
    messagingSenderId: '658506360235',
    projectId: 'v4c-app-72802',
    authDomain: 'v4c-app-72802.firebaseapp.com',
    storageBucket: 'v4c-app-72802.firebasestorage.app',
    measurementId: 'G-5D7SHGGFYP',
  );
}
